### ISSUE TITLE
DOCKERCFG non working password

### ISSUE THREAD

**Issue by camaeel** [DaspawnW/vault-crd#107]
I had password in secret in vault set to `s%*nY*,>E8vT6.+hC_Aw^Yb'i,&<]}m>X[3oDh9\`.

I created vault CRD:
```
apiVersion: koudingspawn.de/v1
kind: Vault
metadata:
  name: gitlab-registry-credentials
spec:
  dockerCfgConfiguration:
    type: KEYVALUEV2
  path: kv-stg/gitlab/kubernetes-prod-user
  type: DOCKERCFG
```

and got event like this:
```
Failed to generate secret with exception Failure executing: POST at: https://10.32.0.1:443/api/v1/namespaces/SOME_NS/secrets. Message: Secret "gitlab-registry-credentials" is invalid: data[.dockercfg]: Invalid value: "<secret contents redacted>": invalid character 'e' after object key:value pair. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=data[.dockercfg], message=Invalid value: "<secret contents redacted>": invalid character 'e' after object key:value pair, reason=FieldValueInvalid, additionalProperties={})], group=null, kind=Secret, name=gitlab-registry-credentials, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Secret "gitlab-registry-credentials" is invalid: data[.dockercfg]: Invalid value: "<secret contents redacted>": invalid character 'e' after object key:value pair, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
```

I suspect there is some issue with one of special characters.
