### ISSUE TITLE
if a `Secret` of the same name as a `Vault` already exists, it does not fail.

### ISSUE THREAD

**Issue by jaywgraves** [DaspawnW/vault-crd#12]
I created this `Secret` via `kubectl apply`
```
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ajayg2
data:
  key1: ZnJvbXNlY3JldA==
```

I then create a `Vault` object that should use the same name.
```
apiVersion: "koudingspawn.de/v1"
kind: Vault
metadata:
  name: ajayg2
spec:
  type: "KEYVALUE"
  path: "secret/infra/jayg"
```

In the logs I see the line `Received action: ADDED for ajayg2 in namespace X`
but `kubectl get secret -o yaml ajayg2` shows me that it has the original secret, not the one from Vault and it does not have `vault.koudingspawn.de/*` annotations.
If I wait for the next Refresh from `vault-crd` and get the yaml again, I see that it has the secret value from Vault and it has the annotations indicating that it is controlled by the CRD.

I feel this is fairly inconsistent.  I think the initial create should fail because it finds a Secret that is not controlled by the CRD.
But if it is going to be added, it needs to update the Secret with the right values immediately and not wait for the first refresh pass.
