### ISSUE TITLE
Vault Token in ENV var

### ISSUE THREAD

**Issue by bgeesaman** [DaspawnW/vault-crd#9]
Neat implementation!  Suggest that you move the `KUBERNETES_VAULT_TOKEN` from a static definition on the ENV of the deployment to a separate secret file that the deployment mounts in with `secretKeyRef`.  Anyone with the ability to get/list deployments will be able to steal the vault token and get all the secrets it has access to.  Fewer roles/clusterroles allow get/list of secrets than deployments, so this improves the access control surrounding that sensitive token.

```
        env:
        - name: KUBERNETES_VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-crd-secret-name
              key: "token"
```
